# permissions for end users to edit jsonnetsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jsonnetsource-editor-role
rules:
- apiGroups:
  - extension.projectsveltos.io
  resources:
  - jsonnetsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.projectsveltos.io
  resources:
  - jsonnetsources/status
  verbs:
  - get
