---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extension.projectsveltos.io
  resources:
  - jsonnetsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.projectsveltos.io
  resources:
  - jsonnetsources/finalizers
  verbs:
  - update
- apiGroups:
  - extension.projectsveltos.io
  resources:
  - jsonnetsources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - buckets/status
  - gitrepositories
  - gitrepositories/status
  - ocirepositories
  - ocirepositories/status
  verbs:
  - get
  - list
  - watch
