apiVersion: extension.projectsveltos.io/v1beta1
kind: JsonnetSource
metadata:
  labels:
    app.kubernetes.io/name: jsonnet-controller
    app.kubernetes.io/managed-by: kustomize
  name: jsonnetsource-sample
spec:
  # TODO(user): Add fields here
